In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
#Read data
df = pd.read_csv("salary matrix.csv")
print("Data imported")

Data imported


In [5]:
df.head()

Depatment  WorkedHours  Certification  YearsExperience  Salary
0  Development         2300              0              1.1   39343
1      Testing         2100              1              1.3   46205
2  Development         2104              2              1.5   37731
3  UX Designer         1200              1              2.0   43525
4      Testing         1254              2              2.2   39891

In [11]:
X= df.iloc[:,0:5].values
#use this format for X. It creates a matrix rather than a series
#matrix is good for appending as multiple columns are included
X.shape

(30, 5)

In [14]:
y = df.iloc[:,4].values
y.shape

(30,)

In [16]:
#Encoding the categorical data

##X has multiple columns with multiple categories. Use One-hot encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:,0] = labelencoder.fit_transform(X[:,0])
X[:,0]

array([0, 1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1,
       2, 0, 2, 2, 1, 0, 1, 2], dtype=object)

In [17]:
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
X

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, 2.30000e+03, 0.00000e+00,
        1.10000e+00, 3.93430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 2.10000e+03, 1.00000e+00,
        1.30000e+00, 4.62050e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 2.10400e+03, 2.00000e+00,
        1.50000e+00, 3.77310e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 1.20000e+03, 1.00000e+00,
        2.00000e+00, 4.35250e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 1.25400e+03, 2.00000e+00,
        2.20000e+00, 3.98910e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 1.23600e+03, 1.00000e+00,
        2.90000e+00, 5.66420e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, 1.45200e+03, 2.00000e+00,
        3.00000e+00, 6.01500e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, 1.78900e+03, 1.00000e+00,
        3.20000e+00, 5.44450e+04],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, 1.64500e+03, 1.00000e+00,
        3.20000e+00, 6.44450e+04],
       [0.00000e+00, 0.00000

In [19]:
#Avoiding dummy variable trap or the Multicollinearity
X = X[:,1:]
X

array([[0.00000e+00, 0.00000e+00, 2.30000e+03, 0.00000e+00, 1.10000e+00,
        3.93430e+04],
       [1.00000e+00, 0.00000e+00, 2.10000e+03, 1.00000e+00, 1.30000e+00,
        4.62050e+04],
       [0.00000e+00, 0.00000e+00, 2.10400e+03, 2.00000e+00, 1.50000e+00,
        3.77310e+04],
       [0.00000e+00, 1.00000e+00, 1.20000e+03, 1.00000e+00, 2.00000e+00,
        4.35250e+04],
       [1.00000e+00, 0.00000e+00, 1.25400e+03, 2.00000e+00, 2.20000e+00,
        3.98910e+04],
       [0.00000e+00, 1.00000e+00, 1.23600e+03, 1.00000e+00, 2.90000e+00,
        5.66420e+04],
       [0.00000e+00, 0.00000e+00, 1.45200e+03, 2.00000e+00, 3.00000e+00,
        6.01500e+04],
       [1.00000e+00, 0.00000e+00, 1.78900e+03, 1.00000e+00, 3.20000e+00,
        5.44450e+04],
       [0.00000e+00, 1.00000e+00, 1.64500e+03, 1.00000e+00, 3.20000e+00,
        6.44450e+04],
       [0.00000e+00, 1.00000e+00, 1.25800e+03, 0.00000e+00, 3.70000e+00,
        5.71890e+04],
       [1.00000e+00, 0.00000e+00, 1.47800e+03, 3.0

In [20]:
#Splitting the df into training and test sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 0)

In [22]:
#Fitting Multiple Linear Regr model to training set

from sklearn.linear_model import LinearRegression
reg = LinearRegression() 
#No parameters are required for Linear Regr.

reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
#Predicting the Test set results
y_pred = reg.predict(X_test)
y_pred

array([ 37731., 122391.,  57081.,  63218., 116969., 109431., 112635.,
        55794.,  83088.])

In [28]:
#Visulaising the results
#plt.figure(figsize = (20,10))
#plt.scatter(X,y) #Error
#x and y must be the same size

#plt.plot(X,y_pred)

#ValueError: x and y must have same first dimension, but have shapes (30, 6) and (9,)

#### R-squared or Coefficient of Determination

In [31]:
from sklearn.metrics import accuracy_score
print('Multiple Regression R squared": %.4f' % reg.score(X_test, y_test))
print("So, in our model, %.4f of the variability in Y can be explained using X. That is really exciting."% reg.score(X_test, y_test))

Multiple Regression R squared": 1.0000
So, in our model, 1.0000 of the variability in Y can be explained using X. That is really exciting.
