In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('data.xlsx')
print("Data imported")

Data imported


In [3]:
df.head(20)

Country   Age   Salary Purchased
0  France  44.0  72000.0        No
1   Italy  27.0  48000.0       Yes
2  Norway  30.0  54000.0        No
3   Italy  38.0  61000.0        No
4  Norway  40.0      NaN       Yes
5  France  35.0  58000.0       Yes
6   Italy   NaN  52000.0        No
7  France  48.0  79000.0       Yes
8  Norway  50.0  83000.0        No
9  France  37.0  67000.0       Yes

In [4]:
X = df.iloc[:,0]
Y = df.iloc[:,-1]
print('X',X)
print('Y',Y)

X 0    France
1     Italy
2    Norway
3     Italy
4    Norway
5    France
6     Italy
7    France
8    Norway
9    France
Name: Country, dtype: object
Y 0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [6]:
labelencoder = LabelEncoder() #create an object whenever you import a package
X = labelencoder.fit_transform(X)
X

array([0, 1, 2, 1, 2, 0, 1, 0, 2, 0], dtype=int64)

**Cannot use LabelEncoder as we have multiple labels. Labels generated can be misunderstood as ranks for data. Thus use OneHotEncoder for more than 2 categories.**

In [7]:
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing.data:

class OneHotEncoder(sklearn.base.BaseEstimator, sklearn.base.TransformerMixin)
 |  Encode categorical integer features using a one-hot aka one-of-K scheme.
 |  
 |  The input to this transformer should be a matrix of integers, denoting
 |  the values taken on by categorical (discrete) features. The output will be
 |  a sparse matrix where each column corresponds to one possible value of one
 |  feature. It is assumed that input features take on values in the range
 |  [0, n_values).
 |  
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |  
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |  
 |  Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
 |  
 |  Parameters
 |  ----------
 |  n_values : 'auto', int or array of ints
 |      Number of values per feature.
 |

In [8]:
#X = df.iloc[:,0]
#initialise X again before running encoder

X = X.reshape(-1, 1)
#do this to avoid ValueError when running OHE. 

onehotencoder = OneHotEncoder(categorical_features =[0], sparse = False)  #columns with categorical data
X = onehotencoder.fit_transform(X) #.to_array() Not needed as X is reshaped
#convert X into an array before feeding to encoder
print('X\n',X)

X
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


categorical_features : "all" or array of indices or mask
- |      Specify what features are treated as categorical.
- |      - 'all' (default): All features are treated as categorical.
- |      - array of indices: Array of categorical feature indices.

sparse = False
Makes the output more readable