- **Used on features vector when we want the features to be centered on or around 0. **
and it removes **Features Bias **

In [10]:
import numpy as np
from sklearn import preprocessing 
#MinMaxScaler, StandardScaler

In [3]:
data = np.array([[2.2, 5.9, -1.8], [5.4, -3.2, -5.1], [-1.9, 4.2, 3.2]])
data

array([[ 2.2,  5.9, -1.8],
       [ 5.4, -3.2, -5.1],
       [-1.9,  4.2,  3.2]])

In [8]:
#Get mean and STD before and after scaling
print("Mean(before): ", data.mean(axis = 0))
print("STD(before): ", data.std(axis = 0))

Mean(before):  [ 1.9         2.3        -1.23333333]
STD(before):  [2.98775278 3.95052739 3.41207008]


we want **mean to be equal to or around 0**
and **standard dev. to be equal or around 0**

In [19]:
scaled_data = preprocessing.scale(data)

print("Scaled_Data\n\n",scaled_data,"\n")
print("Mean(after): \n", scaled_data.mean(axis = 0),"\n")
print("STD(after): \n", scaled_data.std(axis = 0),"\n")

Scaled_Data

 [[ 0.10040991  0.91127074 -0.16607709]
 [ 1.171449   -1.39221918 -1.1332319 ]
 [-1.27185891  0.48094844  1.29930899]] 

Mean(after): 
 [0.00000000e+00 0.00000000e+00 7.40148683e-17] 

STD(after): 
 [1. 1. 1.] 



In [34]:
standardised_scaler = preprocessing.StandardScaler()
standardised_data = standardised_scaler.fit_transform(data)

print("Mean = 0, Variance = 1")
print("standardised_data\n\n",standardised_data,"\n")
print("Mean(after): \n", standardised_data.mean(axis = 0),"\n")
print("STD(after): \n", standardised_data.std(axis = 0),"\n")

Mean = 0, Variance = 1
standardised_data

 [[ 0.10040991  0.91127074 -0.16607709]
 [ 1.171449   -1.39221918 -1.1332319 ]
 [-1.27185891  0.48094844  1.29930899]] 

Mean(after): 
 [0.00000000e+00 0.00000000e+00 7.40148683e-17] 

STD(after): 
 [1. 1. 1.] 



In [25]:
#np.std(standardised_data, axis = 0)
#IndexError: tuple index out of range

In [35]:
minmax_scaler = MinMaxScaler()
minmax_data = minmax_scaler.fit_transform(data)
print("Data in the range (0,1)")
print("minmax_data\n\n",minmax_data,"\n")
print("Mean(after): \n", minmax_data.mean(axis = 0),"\n")
print("STD(after): \n", minmax_data.std(axis = 0),"\n")

Data in the range (0,1)
minmax_data

 [[0.56164384 1.         0.39759036]
 [1.         0.         0.        ]
 [0.         0.81318681 1.        ]] 

Mean(after): 
 [0.52054795 0.6043956  0.46586345] 

STD(after): 
 [0.4092812  0.43412389 0.41109278] 



a 0 mean and unit STD, standardises data when one or more feature has a different mean & STD distribution. Else it will manipulate the results 

In [41]:
from sklearn.preprocessing import Normalizer
normal_scaler = Normalizer()
normal_data = normal_scaler.fit_transform(data)

print("Feature date to a Euclidean length =1")
print("Normalised Data:\n\n", normal_data)
print("Mean(after): \n", normal_data.mean(axis = 0),"\n")
print("STD(after): \n", normal_data.std(axis = 0),"\n")

Feature date to a Euclidean length =1
Normalised Data:

 [[ 0.3359268   0.90089461 -0.2748492 ]
 [ 0.6676851  -0.39566524 -0.63059148]
 [-0.33858465  0.74845029  0.57024784]]
Mean(after): 
 [ 0.22167575  0.41789322 -0.11173095] 

STD(after): 
 [0.41867623 0.57862933 0.50362648] 

